pipeline:
  name: Build CRUD-App
  identifier: Build_Arjunapk_CRUD_App_1720865241553
  projectIdentifier: Node_App
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720855672475
        repoName: Arjunapk/CRUD-App
        build: <+input>
